"""add feed consecutive poll failures counter

Revision ID: b69b210f8341
Revises: 2860c5960bc3
Create Date: 2026-09-04 16:28:48.006607
"""
from alembic import op
import sqlalchemy as sa


revision = 'b69b210f8341'
down_revision = '2860c5960bc3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Adjusted: SQLite can't add a NOT NULL column without a default to a
    # table that already has rows, so give it a server default to backfill
    # existing feeds, then drop the server default (the model only sets a
    # Python-side default of 0 for new rows).
    with op.batch_alter_table('feeds', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('consecutive_poll_failures', sa.Integer(), nullable=False, server_default='0')
        )
    with op.batch_alter_table('feeds', schema=None) as batch_op:
        batch_op.alter_column('consecutive_poll_failures', server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feeds', schema=None) as batch_op:
        batch_op.drop_column('consecutive_poll_failures')

    # ### end Alembic commands ###
