"""initial schema

Revision ID: e80f3c8e2563
Revises: 
Create Date: 2026-08-30 14:01:48.012420
"""
from alembic import op
import sqlalchemy as sa

import hushcast.models


revision = 'e80f3c8e2563'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feeds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('author', sa.Text(), nullable=True),
    sa.Column('link', sa.Text(), nullable=True),
    sa.Column('etag', sa.Text(), nullable=True),
    sa.Column('last_modified', sa.Text(), nullable=True),
    sa.Column('last_polled_at', hushcast.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('poll_error', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('whitelisted', sa.Boolean(), nullable=False),
    sa.Column('detection_hints', sa.Text(), nullable=True),
    sa.Column('learned_hints', sa.Text(), nullable=True),
    sa.Column('hints_distilled_at', hushcast.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', hushcast.models.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feeds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feeds_slug'), ['slug'], unique=True)

    op.create_table('settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('episodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feed_id', sa.Integer(), nullable=False),
    sa.Column('guid', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('published_at', hushcast.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('description_html', sa.Text(), nullable=False),
    sa.Column('source_enclosure_url', sa.Text(), nullable=False),
    sa.Column('source_enclosure_type', sa.Text(), nullable=False),
    sa.Column('source_enclosure_length', sa.Integer(), nullable=True),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('status_detail', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('original_path', sa.Text(), nullable=True),
    sa.Column('processed_path', sa.Text(), nullable=True),
    sa.Column('processed_bytes', sa.Integer(), nullable=True),
    sa.Column('processed_duration_s', sa.Float(), nullable=True),
    sa.Column('ad_seconds_removed', sa.Float(), nullable=True),
    sa.Column('created_at', hushcast.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', hushcast.models.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], ['feeds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feed_id', 'guid', name='uq_episode_feed_guid')
    )
    with op.batch_alter_table('episodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_episodes_feed_id'), ['feed_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_episodes_status'), ['status'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('step', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', hushcast.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('finished_at', hushcast.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('log_text', sa.Text(), nullable=False),
    sa.Column('metrics_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_episode_id'), ['episode_id'], unique=False)

    op.create_table('llm_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('request_json', sa.Text(), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=False),
    sa.Column('params_json', sa.Text(), nullable=True),
    sa.Column('response_json', sa.Text(), nullable=True),
    sa.Column('events_json', sa.Text(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('finish_reason', sa.String(length=30), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('elapsed_s', sa.Float(), nullable=False),
    sa.Column('created_at', hushcast.models.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_calls_episode_id'), ['episode_id'], unique=False)

    op.create_table('segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('start_s', sa.Float(), nullable=False),
    sa.Column('end_s', sa.Float(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('kept', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('corrected_at', hushcast.models.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('segments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_segments_episode_id'), ['episode_id'], unique=False)

    op.create_table('transcription_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('part', sa.Integer(), nullable=False),
    sa.Column('parts', sa.Integer(), nullable=False),
    sa.Column('audio_s', sa.Float(), nullable=True),
    sa.Column('upload_bytes', sa.Integer(), nullable=True),
    sa.Column('elapsed_s', sa.Float(), nullable=False),
    sa.Column('created_at', hushcast.models.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transcription_calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transcription_calls_episode_id'), ['episode_id'], unique=False)

    op.create_table('transcripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('language', sa.Text(), nullable=True),
    sa.Column('json_path', sa.Text(), nullable=False),
    sa.Column('created_at', hushcast.models.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('episode_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transcripts')
    with op.batch_alter_table('transcription_calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transcription_calls_episode_id'))

    op.drop_table('transcription_calls')
    with op.batch_alter_table('segments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_segments_episode_id'))

    op.drop_table('segments')
    with op.batch_alter_table('llm_calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_calls_episode_id'))

    op.drop_table('llm_calls')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_episode_id'))

    op.drop_table('jobs')
    with op.batch_alter_table('episodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_episodes_status'))
        batch_op.drop_index(batch_op.f('ix_episodes_feed_id'))

    op.drop_table('episodes')
    op.drop_table('settings')
    with op.batch_alter_table('feeds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feeds_slug'))

    op.drop_table('feeds')
    # ### end Alembic commands ###
